name: 'Cron fetch data'
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  cron-fetch:
    uses: ./.github/workflows/base.yml
    secrets: inherit
    with:
      commit_msg: 'Update data automatically'
